In [1]:
import pandas as pd
from sqlalchemy import create_engine

In [2]:
csv_file = "Resources/NFL_2018_49ers.csv"
SF49ers_2018 = pd.read_csv(csv_file)
SF49ers_2018.head()

,Round Number,Date,Location,Home Team,Away Team,Result
0,1,09/09/2018 10:00,U.S. Bank Stadium,Minnesota Vikings,San Francisco 49ers,24 - 16
1,2,16/09/2018 13:05,Levi's Stadium,San Francisco 49ers,Detroit Lions,30 - 27
2,3,23/09/2018 10:00,Arrowhead Stadium,Kansas City Chiefs,San Francisco 49ers,38 - 27
3,4,30/09/2018 13:25,StubHub Center,Los Angeles Chargers,San Francisco 49ers,29 - 27
4,5,07/10/2018 13:25,Levi's Stadium,San Francisco 49ers,Arizona Cardinals,18 - 28

In [3]:
csv_file = "Resources/NFL_2017_49ers.csv"
SF49ers_2017 = pd.read_csv(csv_file)
SF49ers_2017.head()

,Round Number,Date,Location,Home Team,Away Team,Result
0,1,10/09/2017 13:25,Levi's Stadium,San Francisco 49ers,Carolina Panthers,3 - 23
1,2,17/09/2017 13:25,CenturyLink Field,Seattle Seahawks,San Francisco 49ers,12 - 9
2,3,21/09/2017 17:25,Levi's Stadium,San Francisco 49ers,Los Angeles Rams,39 - 41
3,4,01/10/2017 13:05,U of Phoenix Stadium,Arizona Cardinals,San Francisco 49ers,18 - 15
4,5,08/10/2017 10:00,Lucas Oil Stadium,Indianapolis Colts,San Francisco 49ers,26 - 23

In [4]:
csv_file = "Resources/NFL_2016_49ers.csv"
SF49ers_2016 = pd.read_csv(csv_file)
SF49ers_2016.head()

,Round Number,Date,Location,Home Team,Away Team,Result
0,1,12/09/2016 19:20,Levi's Stadium,San Francisco 49ers,Los Angeles Rams,28 - 0
1,2,18/09/2016 10:00,Bank of America Stadium,Carolina Panthers,San Francisco 49ers,46 - 27
2,3,25/09/2016 13:05,CenturyLink Field,Seattle Seahawks,San Francisco 49ers,37 - 18
3,4,02/10/2016 13:25,Levi's Stadium,San Francisco 49ers,Dallas Cowboys,17 - 24
4,5,06/10/2016 17:25,Levi's Stadium,San Francisco 49ers,Arizona Cardinals,21 - 33

In [42]:
csv_file = "Resources/49ers_data.csv"
SF49ers_Data = pd.read_csv(csv_file)
SF49ers_Data.head()

,Date,Location,Home Team,Away Team,Result
0,9/9/18 10:00,U.S. Bank Stadium,Minnesota Vikings,San Francisco 49ers,24 - 16
1,16/09/2018 13:05,Levi's Stadium,San Francisco 49ers,Detroit Lions,30 - 27
2,23/09/2018 10:00,Arrowhead Stadium,Kansas City Chiefs,San Francisco 49ers,38 - 27
3,30/09/2018 13:25,StubHub Center,Los Angeles Chargers,San Francisco 49ers,29 - 27
4,7/10/18 13:25,Levi's Stadium,San Francisco 49ers,Arizona Cardinals,18 - 28

In [5]:
csv_file = "Resources/sportsref_data.csv"
sportsref = pd.read_csv(csv_file)
sportsref

,Rk,Tm,Year,Date,Time,LTime,Unnamed: 6,Opp,Week,G#,...,OU Result,Cmp,Att,Cmp%,Yds,TD,Int,Sk,Yds.1,Rate
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1.0,SFO,2013.0,9/8/13,4:26,1:26,NaN,GNB,1.0,1.0,...,over,27.0,39.0,69.2,404.0,3.0,0.0,2.0,8.0,128.6
2,2.0,SFO,2018.0,11/1/18,8:20,5:20,NaN,OAK,9.0,9.0,...,under,16.0,22.0,72.7,262.0,3.0,0.0,0.0,0.0,151.9
3,3.0,SFO,2013.0,11/25/13,8:40,8:40,@,WAS,12.0,11.0,...,under,15.0,24.0,62.5,228.0,3.0,0.0,2.0,7.0,133.3
4,4.0,SFO,2018.0,12/30/18,4:25,1:25,@,LAR,17.0,16.0,...,over,23.0,33.0,69.7,264.0,3.0,3.0,3.0,18.0,85.9
5,5.0,SFO,2016.0,11/27/16,1:00,1:00,@,MIA,12.0,11.0,...,over,29.0,46.0,63.0,282.0,3.0,1.0,2.0,14.0,92.8
6,6.0,SFO,2014.0,10/13/14,8:30,7:30,@,STL,6.0,6.0,...,over,22.0,35.0,62.9,343.0,3.0,0.0,0.0,0.0,123.9
7,7.0,SFO,2017.0,12/31/17,4:25,1:25,@,LAR,17.0,16.0,...,over,20.0,33.0,60.6,292.0,2.0,2.0,0.0,0.0,84.4
8,8.0,SFO,2015.0,12/27/15,1:03,1:03,@,DET,16.0,15.0,...,over,22.0,33.0,66.7,201.0,2.0,0.0,3.0,24.0,103.2
9,9.0,SFO,2014.0,12/28/14,4:25,1:25,NaN,ARI,17.0,16.0,...,under,15.0,26.0,57.7,189.0,2.0,0.0,1.0,15.0,106.1
10,10.0,SFO,2015.0,9/20/15,1:02,1:02,@,PIT,2.0,2.0,...,over,33.0,46.0,71.7,298.0,2.0,0.0,5.0,37.0,103.4
11,11.0,SFO,2017.0,11/12/17,4:25,1:25,NaN,NYG,10.0,10.0,...,over,19.0,25.0,76.0,288.0,2.0,1.0,0.0,0.0,123.4
12,12.0,SFO,2018.0,9/16/18,4:05,1:05,NaN,DET,2.0,2.0,...,over,18.0,26.0,69.2,156.0,2.0,0.0,6.0,50.0,110.4
13,13.0,SFO,2017.0,12/24/17,4:05,1:05,NaN,JAX,16.0,15.0,...,over,21.0,30.0,70.0,238.0,2.0,1.0,1.0,4.0,101.8
14,14.0,SFO,2015.0,10/11/15,8:31,8:31,@,NYG,5.0,5.0,...,over,23.0,35.0,65.7,256.0,2.0,0.0,2.0,6.0,106.4
15,15.0,SFO,2015.0,10/18/15,4:25,1:25,NaN,BAL,6.0,6.0,...,over,16.0,27.0,59.3,326.0,2.0,0.0,3.0,14.0,126.5
16,16.0,SFO,2016.0,11/6/16,4:05,1:05,NaN,NOR,9.0,8.0,...,over,24.0,39.0,61.5,393.0,2.0,1.0,1.0,5.0,101.8
17,17.0,SFO,2016.0,9/18/16,1:03,1:03,@,CAR,2.0,2.0,...,over,17.0,36.0,47.2,237.0,2.0,2.0,2.0,6.0,64.2
18,18.0,SFO,2016.0,11/20/16,4:25,1:25,NaN,NWE,11.0,10.0,...,under,16.0,30.0,53.3,177.0,2.0,0.0,5.0,29.0,93.3
19,19.0,SFO,2016.0,12/18/16,4:05,4:05,@,ATL,15.0,14.0,...,over,20.0,33.0,60.6,165.0,2.0,0.0,2.0,18.0,93.6
20,20.0,SFO,2016.0,12/24/16,4:25,1:25,@,LAR,16.0,15.0,...,over,28.0,37.0,75.7,253.0,2.0,1.0,4.0,13.0,100.4
21,21.0,SFO,2017.0,9/21/17,8:25,5:25,NaN,LAR,3.0,3.0,...,over,23.0,37.0,62.2,308.0,2.0,1.0,4.0,24.0,95.3
22,22.0,SFO,2015.0,11/8/15,4:05,1:05,NaN,ATL,9.0,9.0,...,under,15.0,26.0,57.7,185.0,2.0,2.0,0.0,0.0,73.4
23,23.0,SFO,2017.0,10/8/17,1:00,1:00,@,IND,5.0,5.0,...,over,29.0,46.0,63.0,336.0,2.0,0.0,2.0,17.0,99.5
24,24.0,SFO,2018.0,9/23/18,1:00,12:00,@,KAN,3.0,3.0,...,over,20.0,30.0,66.7,228.0,2.0,0.0,4.0,23.0,111.5
25,25.0,SFO,2018.0,12/2/18,4:25,5:20,@,SEA,13.0,12.0,...,over,30.0,48.0,62.5,386.0,2.0,1.0,3.0,28.0,92.9
26,26.0,SFO,2013.0,10/13/13,4:25,1:25,NaN,ARI,6.0,6.0,...,over,16.0,29.0,55.2,238.0,2.0,1.0,2.0,14.0,90.9
27,27.0,SFO,2013.0,11/17/13,4:25,3:25,@,NOR,11.0,10.0,...,under,17.0,31.0,54.8,115.0,2.0,1.0,3.0,12.0,71.3
28,28.0,SFO,2018.0,9/30/18,4:25,1:25,@,LAC,4.0,4.0,...,over,23.0,37.0,62.2,288.0,2.0,2.0,1.0,10.0,81.8
29,29.0,SFO,2013.0,12/15/13,1:02,1:02,@,TAM,15.0,14.0,...,over,19.0,29.0,65.5,189.0,2.0,0.0,2.0,14.0,106.8
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
68,68.0,SFO,2015.0,11/22/15,4:27,1:27,@,SEA,11.0,10.0,...,over,22.0,34.0,64.7,247.0,1.0,0.0,2.0,17.0,96.1
69,69.0,SFO,2016.0,10/2/16,4:25,1:25,NaN,DAL,4.0,4.0,...,under,16.0,23.0,69.6,189.0,1.0,1.0,1.0,7.0,90.7
70,70.0,SFO,2016.0,9/12/16,10:20,7:20,NaN,LAR,1.0,1.0,...,under,22.0,35.0,62.9,170.0,1.0,0.0,0.0,0.0,84.2
71,71.0,SFO,2015.0,1/3/16,4:25,1:25,NaN,STL,17.0,16.0,...,under,28.0,44.0,63.6,350.0,1.0,1.0,1.0,4.0,86.4
72,72.0,SFO,2013.0,10/27/13,1:07,5:07,@,JAX,8.0,8.0,...,over,11.0,17.0,64.7,177.0,1.0,0.0,0.0,0.0,119.0
73,73.0,SFO,2015.0,12/20/15,4:25,1:25,NaN,CIN,15.0,14.0,...,under,30.0,50.0,60.0,263.0,1.0,3.0,4.0,32.0,55.7
74,74.0,SFO,2015.0,12/13/15,1:02,1:02,@,CLE,14.0,13.0,...,under,18.0,28.0,64.3,150.0,1.0,0.0,9.0,44.0,89.9
75,75.0,SFO,2015.0,12/6/15,1:02,12:02,@,CHI,13.0,12.0,...,over,18.0,32.0,56.3,170.0,1.0,0.0,4.0,26.0,81.5
76,76.0,SFO,2015.0,11/29/15,4:05,1:05,NaN,ARI,12.0,11.0,...,under,25.0,36.0,69.4,301.0,1.0,1.0,2.0,17.0,92.5
77,77.0,SFO,2013.0,11/10/13,4:05,1:05,NaN,CAR,10.0,9.0,...,under,11.0,22.0,50.0,46.0,0.0,1.0,6.0,45.0,37.3
78,78.0,SFO,2018.0,12/23/18,4:05,1:05,NaN,CHI,16.0,15.0,...,under,22.0,38.0,57.9,232.0,0.0,1.0,1.0,9.0,64.8
79,79.0,SFO,2016.0,12/4/16,1:00,12:00,@,CHI,13.0,12.0,...,under,5.0,15.0,33.3,6.0,0.0,0.0,6.0,33.0,42.4
80,80.0,SFO,2013.0,9/15/13,8:31,5:31,@,SEA,2.0,2.0,...,under,13.0,28.0,46.4,107.0,0.0,3.0,3.0,20.0,17.1
81,81.0,SFO,2013.0,9/22/13,4:25,1:25,NaN,IND,3.0,3.0,...,under,13.0,27.0,48.1,139.0,0.0,1.0,3.0,11.0,48.2
82,82.0,SFO,2013.0,10/20/13,4:06,3:06,@,TEN,7.0,7.0,...,over,13.0,21.0,61.9,196.0,0.0,0.0,2.0,3.0,92.6
83,83.0,SFO,2017.0,10/22/17,4:05,1:05,NaN,DAL,7.0,7.0,...,over,22.0,38.0,57.9,187.0,0.0,0.0,5.0,48.0,70.8
84,84.0,SFO,2017.0,9/10/17,4:25,1:25,NaN,CAR,1.0,1.0,...,under,24.0,35.0,68.6,166.0,0.0,1.0,4.0,27.0,67.1
85,85.0,SFO,2017.0,9/17/17,4:25,1:25,@,SEA,2.0,2.0,...,under,15.0,27.0,55.6,89.0,0.0,1.0,2.0,10.0,46.7
86,86.0,SFO,2017.0,10/1/17,4:05,2:05,@,ARI,4.0,4.0,...,under,24.0,49.0,49.0,210.0,0.0,1.0,3.0,24.0,52.3
87,87.0,SFO,2015.0,11/1/15,1:00,12:00,@,STL,8.0,8.0,...,under,20.0,41.0,48.8,151.0,0.0,0.0,3.0,11.0,58.1
88,88.0,SFO,2015.0,10/22/15,8:26,5:26,NaN,SEA,7.0,7.0,...,under,13.0,24.0,54.2,81.0,0.0,0.0,6.0,43.0,61.3
89,89.0,SFO,2015.0,10/4/15,4:25,1:25,NaN,GNB,4.0,4.0,...,under,13.0,25.0,52.0,119.0,0.0,1.0,6.0,41.0,48.6
90,90.0,SFO,2017.0,11/5/17,4:05,1:05,NaN,ARI,9.0,9.0,...,under,24.0,51.0,47.1,266.0,0.0,1.0,5.0,28.0,54.9
91,91.0,SFO,2015.0,9/27/15,4:05,1:05,@,ARI,3.0,3.0,...,over,9.0,19.0,47.4,53.0,0.0,4.0,2.0,14.0,14.5
92,92.0,SFO,2015.0,9/14/15,10:20,7:20,NaN,MIN,1.0,1.0,...,under,17.0,26.0,65.4,165.0,0.0,0.0,1.0,0.0,83.0
93,93.0,SFO,2017.0,12/3/17,1:00,12:00,@,CHI,13.0,12.0,...,under,26.0,37.0,70.3,278.0,0.0,1.0,2.0,15.0,80.7
94,94.0,SFO,2014.0,12/14/14,4:26,1:26,@,SEA,15.0,14.0,...,under,11.0,19.0,57.9,105.0,0.0,0.0,6.0,36.0,73.4
95,95.0,SFO,2014.0,11/27/14,8:31,5:31,NaN,SEA,13.0,12.0,...,under,16.0,29.0,55.2,100.0,0.0,2.0,4.0,21.0,33.7
96,96.0,SFO,2016.0,9/25/16,4:05,1:05,@,SEA,3.0,3.0,...,over,14.0,25.0,56.0,119.0,0.0,1.0,0.0,0.0,51.9
97,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [6]:
sportsref.columns

Index(['Rk', 'Tm', 'Year', 'Date', 'Time', 'LTime', 'Unnamed: 6', 'Opp',
       'Week', 'G#', 'Day', 'Result', 'OT', 'Spread', 'vs. Line', 'Over/Under',
       'OU Result', 'Cmp', 'Att', 'Cmp%', 'Yds', 'TD', 'Int', 'Sk', 'Yds.1',
       'Rate'],
      dtype='object')

In [7]:
#rename fields
sportsref.rename(columns={'Rk':'Rank',
                          'Tm':'Team',
                         }, 
                 inplace=True)

In [8]:
sportsref.columns

Index(['Rank', 'Team', 'Year', 'Date', 'Time', 'LTime', 'Unnamed: 6', 'Opp',
       'Week', 'G#', 'Day', 'Result', 'OT', 'Spread', 'vs. Line', 'Over/Under',
       'OU Result', 'Cmp', 'Att', 'Cmp%', 'Yds', 'TD', 'Int', 'Sk', 'Yds.1',
       'Rate'],
      dtype='object')

In [43]:
sportsref_db = sportsref[['Team','Date','Opp','vs. Line','OU Result','Spread']]

#### sportsref_db

In [45]:
pip install psycopg2-binary

Collecting psycopg2-binary
  Downloading https://files.pythonhosted.org/packages/ee/ed/2772267467ba5c21a73d37149da0b49a4343c6646d501dbb1450b492d40a/psycopg2_binary-2.8.3-cp37-cp37m-macosx_10_6_intel.macosx_10_9_intel.macosx_10_9_x86_64.macosx_10_10_intel.macosx_10_10_x86_64.whl (1.5MB)
    100% |████████████████████████████████| 1.6MB 3.4MB/s
Installing collected packages: psycopg2-binary
Successfully installed psycopg2-binary-2.8.3
Note: you may need to restart the kernel to use updated packages.

In [49]:
rds_connection_string = "postgres:postgres@localhost:5432/ETLproject_DB"
engine = create_engine(f'postgresql://{rds_connection_string}')

In [50]:
engine.table.names()

AttributeError: 'Engine' object has no attribute 'table'